### ISSUE TITLE
Data Tidying

### ISSUE THREAD

**Issue by kaijli** [kaijli/313_IPCMS_Lab#1]
Finished tidying data and exported as icpms_merge.rds and aa_merge.rds in data folder @julianefry @vestoj

**Comment by vestoj** [comment]
Great work! Your code looks perfect, I wasn't able to check the data files since they were in .rds format not .csv, but you must have left lab before we figured out .csv files work better for GitHub and that's totally okay!

**Comment by vestoj** [comment]
Also, good to know that if you @ someone you don't have to invite them as a collaborator to the repository! Very useful information to know for the future!
